INSERT INTO "Artist" ("artistId", "genreId", "createdAt", "updatedAt") VALUES('2uWcrwgWmZcQc3IPBs3tfU', 'k-pop girl group', NOW(), NOW()),
('0qlWcS66ohOIi0M8JZwPft', 'k-pop girl group', NOW(), NOW()),
('2019zR22qK2RBvCqtudBaI', 'k-pop girl group', NOW(), NOW()),
('4SpbR6yFEvexJuaBpgAU5p', 'k-pop girl group', NOW(), NOW()),
('2AfmfGFbe0A0WsTYm0SDTx', 'k-pop girl group', NOW(), NOW()),
('6rJqqRce0Kvo2dJUXoHleC', 'country rock', NOW(), NOW()),
('3KonOYiLsU53m4yT7gNotP', 'k-pop boy group', NOW(), NOW()),
('5qRSs6mvI17zrkJpOHkCoM', 'k-pop boy group', NOW(), NOW()),
('6YVMFz59CuY7ngCxTxjpxE', 'k-pop girl group', NOW(), NOW()),
('3qNVuliS40BLgXGxhdBdqu', 'k-pop', NOW(), NOW()),
('3HqSLMAZ3g3d5poNaI7GOU', 'pop', NOW(), NOW()),
('6RHTUrRF63xao58xh9FXYJ', 'k-pop girl group', NOW(), NOW()),
('6HvZYsbFfjnjFrWF950C9d', 'k-pop girl group', NOW(), NOW()),
('2dd5mrQZvg6SmahdgVKDzh', 'korean old school hip hop', NOW(), NOW()),
('6udveWUgX4vu75FF0DTrXV', 'korean r&b', NOW(), NOW()),
('6HaGTQPmzraVmaVxvz6EUc', 'k-pop', NOW(), NOW()),
('3Cv2vi3WTl8VZOTdrBkKdM', 'k-pop girl group', NOW(), NOW()),
('24nUVBIlCGi4twz4nYxJum', 'k-pop girl group', NOW(), NOW()),
('13kJgvU22LHMsJtGWLmx7W', 'k-pop girl group', NOW(), NOW()),
('1xs6WFotNQSXweo0GXrS0O', 'k-pop girl group', NOW(), NOW()),
('6OwKE9Ez6ALxpTaKcT5ayv', 'k-pop', NOW(), NOW()),
('5vGoWnZO65NBgiZYBmi3iW', 'k-pop', NOW(), NOW()),
('7F1iAHRYxR3MY7yAEuFqgL', '', NOW(), NOW()),
('0VMFTqmv0hYlWruyBERT95', 'singer-songwriter pop', NOW(), NOW()),
('250b0Wlc5Vk0CoUsaCY84M', 'k-pop', NOW(), NOW()),
('5L1lO4eRHmJ7a0Q6csE5cT', 'k-pop', NOW(), NOW()),
('3eVa5w3URK5duf6eyVDbu9', 'k-pop', NOW(), NOW()),
('1iyFL3CRuKW7PXgPH4VxSP', 'k-pop boy group', NOW(), NOW()),
('6UZ0ba50XreR4TM8u322gs', 'k-pop', NOW(), NOW()),
('4yiB30K5scGkjmAgHGIH8Y', '', NOW(), NOW()),
('1SIocsqdEefUTE6XKGUiVS', '5th gen k-pop', NOW(), NOW()),
('6S3tOdgtc5qz16hwmMjEBN', '5th gen k-pop', NOW(), NOW()),
('5DuzBeOgFwViFcv00Q5PFb', 'k-pop boy group', NOW(), NOW());